import React from "react";
import { notFound } from "next/navigation";
import { Award, Printer } from "lucide-react";
import { getSharedReport } from "@/lib/actions/interviews";
import RubricBreakdown from "@/components/interview/RubricBreakdown";
import PrintButton from "./_components/PrintButton";

export const metadata = {
  title: "Shared interview report — SkillForge AI",
  robots: { index: false, follow: false },
};

const ratingColor = (rating) => {
  const n = Number(rating);
  if (Number.isNaN(n)) return "text-gray-600";
  if (n >= 8) return "text-green-600";
  if (n >= 5) return "text-yellow-600";
  return "text-red-600";
};

export default async function SharedReportPage({ params }) {
  const report = await getSharedReport(params.token);
  if (!report) notFound();

  const scored = report.answers.filter((a) => typeof a.rating === "number");
  const average = scored.length
    ? (scored.reduce((s, a) => s + a.rating, 0) / scored.length).toFixed(1)
    : null;

  return (
    <div className="mx-auto max-w-3xl px-4 py-10 print:py-0">
      <div className="mb-6 flex items-start justify-between">
        <div>
          <p className="text-sm font-medium uppercase tracking-wide text-indigo-600">
            SkillForge AI — Interview Report
          </p>
          <h1 className="mt-1 text-2xl font-bold text-gray-900">
            {report.jobPosition}
          </h1>
          <p className="text-sm text-gray-500">
            {report.jobExperience} yrs experience ·{" "}
            {new Date(report.createdAt).toLocaleDateString()}
          </p>
        </div>
        <PrintButton />
      </div>

      <div className="mb-8 flex items-center gap-4 rounded-lg border bg-white p-5">
        <Award className="h-10 w-10 text-indigo-600" />
        <div>
          <p className="text-sm text-gray-500">Overall rating</p>
          <p className={`text-3xl font-bold ${ratingColor(average)}`}>
            {average ? `${average}/10` : "N/A"}
          </p>
        </div>
        <div className="ml-auto text-right">
          <p className="text-sm text-gray-500">Questions</p>
          <p className="text-3xl font-bold text-gray-800">
            {report.answers.length}
          </p>
        </div>
      </div>

      <div className="space-y-4">
        {report.answers.map((a, i) => (
          <div key={a.id} className="rounded-lg border bg-white p-5">
            <div className="flex items-start justify-between gap-4">
              <h2 className="font-semibold text-gray-800">
                Q{i + 1}. {a.question}
              </h2>
              <span className={`shrink-0 font-bold ${ratingColor(a.rating)}`}>
                {a.rating ?? "N/A"}/10
              </span>
            </div>
            {a.feedback ? (
              <p className="mt-3 rounded-md bg-blue-50 p-3 text-sm text-gray-700">
                {a.feedback}
              </p>
            ) : null}
            <RubricBreakdown
              className="mt-4"
              scores={{
                correctness: a.scoreCorrectness,
                clarity: a.scoreClarity,
                depth: a.scoreDepth,
                communication: a.scoreCommunication,
              }}
            />
          </div>
        ))}
      </div>

      <p className="mt-8 text-center text-xs text-gray-400">
        Generated by SkillForge AI · This is a read-only shared report.
      </p>
    </div>
  );
}
